name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run: npm install -g typescript
    - run: npm run migration:run
    - run: tsc
    - run: pm2 restart ecosystem.config.js